id: IFC692161
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T16:09:10+00:00'
last_modified: '2022-06-08T17:03:25.965125+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01619
  title: ཉེར་བརྒྱུད་ཐུགས་རྗེ་ཆེན་པོའི་བསྒོམ་བཟླས་ཀྱི་ངག་འདོན
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEA4:
      image_group_id: I00KG02876
      title: ''
      total_pages: 10
      order: 1
      base_file: EEA4.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
